aspnet/MvcPrecompilation

README.md

Add a AppVeyor link to README

---

test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Tests/ApplicationConsumingPrecompiledViews.cs

This works around issues where we attempt to build the application for desktop in xplat

Don't target desktop in ClassLibraryWithPrecompiledViews

---

MvcPrecompilation.sln
src/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Design/Internal/PrecompilationApplication.cs
src/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Design/Internal/PrecompileRunCommand.cs
src/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Tools/Internal/PrecompileDispatchCommand.cs
src/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Tools/project.json
test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Design.Test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Design.Test.xproj
test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Design.Test/PrecompileRunCommandTest.cs
test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Design.Test/project.json
test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.FunctionalTests/PublishWithEmbedViewSourcesTest.cs
test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Tools.Test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Tools.Test.xproj
test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Tools.Test/PrecompileDispatchCommandTest.cs
test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Tools.Test/project.json

Adding tests for command line parsing

---

TestApps.sln
src/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Tools/project.json
test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.FunctionalTests/Resources/SimpleAppDesktopOnly.Home.Index.txt
test/Microsoft.AspNetCore.Mvc.Razor.Precompilation.FunctionalTests/SimpleAppDesktopOnlyTest.cs
testapps/SimpleAppDesktopOnly/Controllers/HomeController.cs
testapps/SimpleAppDesktopOnly/Program.cs
testapps/SimpleAppDesktopOnly/SimpleAppDesktopOnly.xproj
testapps/SimpleAppDesktopOnly/Startup.cs
testapps/SimpleAppDesktopOnly/Views/Home/Index.cshtml
testapps/SimpleAppDesktopOnly/Views/Shared/_Layout.cshtml
testapps/SimpleAppDesktopOnly/Views/_ViewImports.cshtml
testapps/SimpleAppDesktopOnly/Views/_ViewStart.cshtml
testapps/SimpleAppDesktopOnly/project.json

Microsoft.AspNetCore.Mvc.Razor.Precompilation.Tools does not need to target desktop

---

src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools/Internal/PrecompileDispatchCommand.cs
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.Test/project.json
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/ApplicationConsumingPrecompiledViews.cs
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/Infrastructure/ApplicationTestFixture.cs
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/project.json
testapps/ApplicationUsingPrecompiledViewClassLibrary/project.json
testapps/ApplicationWithConfigureMvc/project.json
testapps/ApplicationWithTagHelpers/project.json
testapps/ClassLibraryWithPrecompiledViews/project.json
testapps/PublishWithEmbedViewSources/project.json
testapps/SimpleApp/project.json
testapps/StrongNamedApp/project.json

dotnet-razor-precompile does not work when the application targets netcoreapp1.1

---

test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/project.json

Don't know when the nuget packages will be uploaded. In the mean time we can fix the build with this change.
cc @halter73

Fix build: pin dotnet cli utils version

---

build.ps1
build.sh
build/common.props
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Test.csproj
version.props

The code changes are done, but the tests currently fail. 
cc @pranavkm any ideas?

[wip] prepare 1.1.0 release

---

RazorViewCompilation.sln
pack/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation-x86.csproj
src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.csproj
src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/Program.cs
src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/net451/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/Resources/SimpleAppX86DesktopOnly.Home.Index.txt
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/SimpleAppX86DesktopOnlyTest.cs
testapps/SimpleAppX86DesktopOnly/Controllers/HomeController.cs
testapps/SimpleAppX86DesktopOnly/Program.cs
testapps/SimpleAppX86DesktopOnly/SimpleAppX86DesktopOnly.csproj
testapps/SimpleAppX86DesktopOnly/Startup.cs
testapps/SimpleAppX86DesktopOnly/Views/Home/Index.cshtml

Create an x86 process to target 32-bit applications

---

src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/Internal/PrecompileRunCommand.cs

React to https://github.com/aspnet/Razor/pull/1017
@rynowak @pranavkm FYI

React to razor

---

pack/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation-x86.csproj
src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.csproj
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/ApplicationConsumingPrecompiledViews.cs
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests.csproj
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Test.csproj
testapps/ApplicationUsingPrecompiledViewClassLibrary/ApplicationUsingPrecompiledViewClassLibrary.csproj
testapps/ApplicationUsingRelativePaths/ApplicationUsingRelativePaths.csproj
testapps/ApplicationWithConfigureMvc/ApplicationWithConfigureMvc.csproj
testapps/ApplicationWithCustomInputFiles/ApplicationWithCustomInputFiles.csproj
testapps/ApplicationWithParseErrors/ApplicationWithParseErrors.csproj
testapps/ApplicationWithTagHelpers/ApplicationWithTagHelpers.csproj
testapps/ClassLibraryTagHelper/ClassLibraryTagHelper.csproj
testapps/ClassLibraryWithPrecompiledViews/ClassLibraryWithPrecompiledViews.csproj
testapps/PublishWithEmbedViewSources/PublishWithEmbedViewSources.csproj
testapps/SimpleApp/SimpleApp.csproj
testapps/SimpleAppDesktopOnly/SimpleAppDesktopOnly.csproj
testapps/SimpleAppMvc11/SimpleAppMvc11.csproj
testapps/SimpleAppX86DesktopOnly/SimpleAppX86DesktopOnly.csproj
testapps/StrongNamedApp/StrongNamedApp.csproj

Bump up package versions for 1.1.1-patch release

---

test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/Infrastructure/ApplicationPaths.cs

This PR removes all references to PlatformAbstractions.
Part of aspnet/PlatformAbstractions#50

react to removal of PlatformAbstractions

---

test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/PublishWithEmbedViewSourcesTest.cs
testapps/PublishWithEmbedViewSources/Controllers/HomeController.cs

Move away from `Assembly.Load` to Assembly.LoadFile

---

testapps/ClassLibraryTagHelper/ClassLibraryTagHelper.csproj

React to https://github.com/aspnet/Razor/pull/1415

React to Razor changing target frameworks

---

.travis.yml
appveyor.yml
build/dependencies.props

@ryanbrandenburg @natemcmaster  @muratg @kichalla

Fix Downgrade Warnings

---

src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/common.targets
test/FunctionalTests/ViewCompilationOptionsTest.cs

Copy precompiled pdb to publish directory

---

test/FunctionalTests/Infrastructure/ApplicationTestFixture.cs
test/FunctionalTests/PublishWithDebugTest_CoreCLR.cs
test/FunctionalTests/PublishWithDebugTest_Desktop.cs
test/FunctionalTests/SimpleAppTest_CoreCLR.cs
test/FunctionalTests/ViewCompilationOptionsTest_CoreCLR.cs

Add a test that always publishes in Debug

---

src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.csproj

Fixes https://github.com/aspnet/MvcPrecompilation/issues/159

Remove dependency on Microsoft.NETCore.App from the generated nuspec

---

build/dependencies.props
src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tasks/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tasks.csproj

- Matches version shipping with Visual Studio 15.3

Update MSBuild to 15.3.0-*

---

build/dependencies.props
src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/common.targets
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/Infrastructure/ApplicationDeployer.cs
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/Infrastructure/ApplicationTestFixture.cs
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/Resources/SimpleAppWithAssemblyRenameTest.Home.Index.txt
test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/SimpleAppWithAssemblyRenameTest.cs
testapps/SimpleApp/SimpleApp.csproj
version.props

Add support for AssemblyName when running precompilation

---

build/dependencies.props

These packages were also updated. I'm scanning through the tools repos to make sure everything is updated so there will be 5 more PRs.

September patch version updates

---

src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets
test/FunctionalTests/Infrastructure/ApplicationTestFixture.cs
test/FunctionalTests/PublishForRidTest_CoreCLR.cs

Add support for cross-publishing

---

src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets
test/FunctionalTests/CopyBuildOutputToPublishDirectoryTest_Desktop.cs
test/FunctionalTests/CopyBuildOutputToPublishDirectory_CoreCLR.cs
test/FunctionalTests/CopyOutputSymbolsToPublishDirectoryTest_CoreCLR.cs
test/FunctionalTests/CopyOutputSymbolsToPublishDirectoryTest_Desktop.cs
test/FunctionalTests/Infrastructure/ApplicationTestFixture.cs
test/FunctionalTests/Infrastructure/PublishOnlyDeployer.cs
test/FunctionalTests/ViewCompilationOptionsTest_CoreCLR.cs

Honor CopyBuildOutputToPublishDirectory and CopyOutputSymbolsToPublihhDirectory switches

---

.github/ISSUE_TEMPALTE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

This is done to reduce contributions to this branch as much as possible.

Added default new issue and pull request templates for the branch

---

build/dependencies.props

Missed version update as I was only looking for MVC versions. Any other versions I need to update?

Missed update

---

test/FunctionalTests/CoreCLRTests/RazorSdkUsedTest_CoreCLR.cs

Ignoring broken test

---

build/dependencies.props
korebuild-lock.txt
testapps/ApplicationUsingRelativePaths/ApplicationUsingRelativePaths.csproj
testapps/ApplicationWithConfigureMvc/ApplicationWithConfigureMvc.csproj
testapps/ApplicationWithCustomInputFiles/ApplicationWithCustomInputFiles.csproj
testapps/ApplicationWithParseErrors/ApplicationWithParseErrors.csproj
testapps/ApplicationWithRazorSdkNeitherUsed/ApplicationWithRazorSdkNeitherUsed.csproj
testapps/ApplicationWithRazorSdkPrecompilationUsed/ApplicationWithRazorSdkPrecompilationUsed.csproj
testapps/ApplicationWithRazorSdkUsed/ApplicationWithRazorSdkUsed.csproj
testapps/ApplicationWithTagHelpers/ApplicationWithTagHelpers.csproj
testapps/ClassLibraryWithPrecompiledViews/ClassLibraryWithPrecompiledViews.csproj
testapps/PublishWithEmbedViewSources/PublishWithEmbedViewSources.csproj
testapps/RazorPagesApp/RazorPagesApp.csproj
testapps/SimpleApp/SimpleApp.csproj
testapps/SimpleAppWithAssemblyRename/SimpleAppWithAssemblyRename.csproj
testapps/StrongNamedApp/StrongNamedApp.csproj

Companion to https://github.com/aspnet/Razor/pull/1987

Integrate Web SDK

---

build/dependencies.props
korebuild-lock.txt
test/FunctionalTests/CoreCLRTests/RazorSdkUsedTest_CoreCLR.cs
testapps/ApplicationUsingRelativePaths/ApplicationUsingRelativePaths.csproj
testapps/ApplicationWithConfigureMvc/ApplicationWithConfigureMvc.csproj
testapps/ApplicationWithCustomInputFiles/ApplicationWithCustomInputFiles.csproj
testapps/ApplicationWithParseErrors/ApplicationWithParseErrors.csproj
testapps/ApplicationWithRazorSdkNeitherUsed/ApplicationWithRazorSdkNeitherUsed.csproj
testapps/ApplicationWithRazorSdkPrecompilationUsed/ApplicationWithRazorSdkPrecompilationUsed.csproj
testapps/ApplicationWithRazorSdkUsed/ApplicationWithRazorSdkUsed.csproj
testapps/ApplicationWithTagHelpers/ApplicationWithTagHelpers.csproj
testapps/ClassLibraryWithPrecompiledViews/ClassLibraryWithPrecompiledViews.csproj
testapps/PublishWithEmbedViewSources/PublishWithEmbedViewSources.csproj
testapps/RazorPagesApp/RazorPagesApp.csproj
testapps/SimpleApp/SimpleApp.csproj
testapps/SimpleAppWithAssemblyRename/SimpleAppWithAssemblyRename.csproj
testapps/StrongNamedApp/StrongNamedApp.csproj

* Re-enable skipped Publish_UsesRazorSDK
* Clean up project files
Fixes #241

Update to latest Sdk

---

build/dependencies.props
korebuild-lock.txt
test/FunctionalTests/Resources/ApplicationWithRazorSdkUsed.Home.Index.txt

Fixes https://github.com/aspnet/MvcPrecompilation/issues/248

React to Sdk changes

---

src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets
test/FunctionalTests/DesktopTests/PublishWithDebugTest_Desktop.cs
test/FunctionalTests/DesktopTests/SimpleAppTest_WithAnyCPU_Desktop.cs
test/FunctionalTests/FunctionalTests.csproj

Fixes https://github.com/aspnet/MvcPrecompilation/issues/240

Use x64 binaries when project's targeting AnyCPU

---

build/dependencies.props
testapps/ApplicationWithRazorSdkNeitherUsed/ApplicationWithRazorSdkNeitherUsed.csproj
testapps/ApplicationWithRazorSdkPrecompilationUsed/ApplicationWithRazorSdkPrecompilationUsed.csproj
testapps/ApplicationWithRazorSdkUsed/ApplicationWithRazorSdkUsed.csproj

Use the Razor.Sdk package

---

src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.csproj
src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.nuspec

Part of aspnet/Universe#1083
We want to include symbols of the Task project in the symbols nupkg.

Added nuspec file for Mvc.Razor.ViewCompilation to include symbols

---

build/dependencies.props
test/FunctionalTests/Infrastructure/ApplicationTestFixture.cs

Reacting to https://github.com/aspnet/Hosting/pull/1412

React to IntigrationTesting changes

---

test/FunctionalTests/CoreCLRTests/RazorPagesAppTest_CoreCLR.cs

Fixes https://github.com/aspnet/MvcPrecompilation/issues/285

Consolidate some RazorPages tests

---

testapps/ApplicationWithConfigureMvc/Startup.cs
testapps/ApplicationWithCustomInputFiles/Startup.cs
testapps/ApplicationWithParseErrors/Startup.cs
testapps/ApplicationWithRazorSdkNeitherUsed/Startup.cs
testapps/ApplicationWithRazorSdkPrecompilationUsed/Startup.cs
testapps/ApplicationWithRazorSdkUsed/Startup.cs
testapps/ApplicationWithTagHelpers/Startup.cs
testapps/PublishWithEmbedViewSources/Startup.cs
testapps/RazorPagesApp/Startup.cs
testapps/SimpleApp/Startup.cs
testapps/SimpleAppWithAssemblyRename/Startup.cs
testapps/StrongNamedApp/Startup.cs

They are being obsolete in https://github.com/aspnet/Logging/pull/932

Remove obsolete logging API usages
